services:
  rpaExecutor01:
    image: grpa_lelac:v2.0.0
    container_name: GRPA_001
    restart: unless-stopped
    environment:
      - RPA_EXECUTOR=GRPAE_001
    shm_size: 750m
    volumes:
      - ./automations/GRPAE_001:/app/automations
      - ./screenshots/GRPAE_001:/app/screenshots
      - ./logs/GRPAE_001:/app/logs

  rpaExecutor02:
    image: grpa_lelac:v2.0.0
    container_name: GRPA_002
    restart: unless-stopped
    environment:
      - RPA_EXECUTOR=GRPAE_002
    shm_size: 750m
    volumes:
      - ./automations/GRPAE_002:/app/automations
      - ./screenshots/GRPAE_002:/app/screenshots
      - ./logs/GRPAE_002:/app/logs