services:
  taskwave_worker:
    image: winterowner/taskwave_worker:v0.1.0
    env_file: .env
    container_name: taskwave_worker
    environment:
      CHROME_BIN: /usr/bin/google-chrome
      CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
      DOCKER_MODE: "true"
    ports:
      - "5000:5000"
    shm_size: 750m # 1gb
    restart: unless-stopped

#  OLD
#  rpaExecutor01:
#    image: winterowner/grpa_lelac:latest
#    container_name: GRPAE_01
#    env_file: .env
#    environment:
#      RPA_EXECUTOR: GRPAE_01
#      CHROME_BIN: /usr/bin/google-chrome
#      CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
#      DOCKER_MODE: "true"
#    shm_size: 750m # 1gb
#    restart: unless-stopped
