services:
  rpa_executor01:
    build: .
    container_name: GRPA_001
    restart: unless-stopped
    environment:
      - ENV=docker
      - RPA_EXECUTOR=GRPAE_001
    shm_size: 750m
    volumes:
      - ./automations:/app/automations
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs


