services:
  grpa_api:
    build: .
    container_name: GRPA_API
    restart: unless-stopped
    command: ["uv", "run", "./api/main.py"]
    ports:
      - "80:8000" # Você acessa no navegador por http://localhost
    env_file:
      - .env
    healthcheck:
      # O curl roda dentro do container, então usa localhost:8000
      test: ["CMD", "curl", "-f", "0.0.0.0:8000/health"]
      interval: 5s      # Verifica rápido enquanto você configura
      timeout: 3s
      retries: 50       # Aumentei o limite para te dar tempo de preencher o wizard
      start_period: 10s

  grpa_worker01:
    build: .
    container_name: GRPA_001
    restart: unless-stopped
    command: ["uv", "run", "main.py"] # Omitido se já estiver no Dockerfile
    depends_on:
      grpa_api:
        condition: service_healthy # O segredo está aqui
    env_file:
      - .env
    shm_size: 750m
    volumes:
      - ./automations:/app/automations
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs

  grpa_docs:
    build: ./docs
    container_name: GRPA_DOCS
    restart: unless-stopped
    ports:
      - "3000:80"